/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AttendRouteImport } from './routes/attend'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendRoute = AttendRouteImport.update({
  id: '/attend',
  path: '/attend',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attend': typeof AttendRoute
  '/faq': typeof FaqRoute
  '/programme': typeof ProgrammeRoute
  '/register': typeof RegisterRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attend': typeof AttendRoute
  '/faq': typeof FaqRoute
  '/programme': typeof ProgrammeRoute
  '/register': typeof RegisterRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attend': typeof AttendRoute
  '/faq': typeof FaqRoute
  '/programme': typeof ProgrammeRoute
  '/register': typeof RegisterRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/attend'
    | '/faq'
    | '/programme'
    | '/register'
    | '/speakers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/attend'
    | '/faq'
    | '/programme'
    | '/register'
    | '/speakers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/attend'
    | '/faq'
    | '/programme'
    | '/register'
    | '/speakers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AttendRoute: typeof AttendRoute
  FaqRoute: typeof FaqRoute
  ProgrammeRoute: typeof ProgrammeRoute
  RegisterRoute: typeof RegisterRoute
  SpeakersRoute: typeof SpeakersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attend': {
      id: '/attend'
      path: '/attend'
      fullPath: '/attend'
      preLoaderRoute: typeof AttendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttendRoute: AttendRoute,
  FaqRoute: FaqRoute,
  ProgrammeRoute: ProgrammeRoute,
  RegisterRoute: RegisterRoute,
  SpeakersRoute: SpeakersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
